
package bilokhado.countrysoapclient.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CountryNotFoundException", targetNamespace = "http://tomcatmetrosoap.bilokhado/")
public class CountryNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CountryNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CountryNotFoundException_Exception(String message, CountryNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CountryNotFoundException_Exception(String message, CountryNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: bilokhado.countrysoapclient.webservice.CountryNotFoundException
     */
    public CountryNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
