
package bilokhado.countrysoapclient.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapCountryService", targetNamespace = "http://tomcatmetrosoap.bilokhado/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapCountryService {


    /**
     * 
     * @param arg0
     * @return
     *     returns bilokhado.countrysoapclient.webservice.Country
     * @throws CountryNotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountry", targetNamespace = "http://tomcatmetrosoap.bilokhado/", className = "bilokhado.countrysoapclient.webservice.GetCountry")
    @ResponseWrapper(localName = "getCountryResponse", targetNamespace = "http://tomcatmetrosoap.bilokhado/", className = "bilokhado.countrysoapclient.webservice.GetCountryResponse")
    @Action(input = "http://tomcatmetrosoap.bilokhado/SoapCountryService/getCountryRequest", output = "http://tomcatmetrosoap.bilokhado/SoapCountryService/getCountryResponse", fault = {
        @FaultAction(className = CountryNotFoundException.class, value = "http://tomcatmetrosoap.bilokhado/SoapCountryService/getCountry/Fault/CountryNotFoundException")
    })
    public Country getCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CountryNotFoundException
    ;

    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileData", targetNamespace = "http://tomcatmetrosoap.bilokhado/", className = "bilokhado.countrysoapclient.webservice.GetFileData")
    @ResponseWrapper(localName = "getFileDataResponse", targetNamespace = "http://tomcatmetrosoap.bilokhado/", className = "bilokhado.countrysoapclient.webservice.GetFileDataResponse")
    @Action(input = "http://tomcatmetrosoap.bilokhado/SoapCountryService/getFileDataRequest", output = "http://tomcatmetrosoap.bilokhado/SoapCountryService/getFileDataResponse")
    public byte[] getFileData();

    /**
     * 
     * @return
     *     returns java.util.List<bilokhado.countrysoapclient.webservice.Country>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountries", targetNamespace = "http://tomcatmetrosoap.bilokhado/", className = "bilokhado.countrysoapclient.webservice.GetCountries")
    @ResponseWrapper(localName = "getCountriesResponse", targetNamespace = "http://tomcatmetrosoap.bilokhado/", className = "bilokhado.countrysoapclient.webservice.GetCountriesResponse")
    @Action(input = "http://tomcatmetrosoap.bilokhado/SoapCountryService/getCountriesRequest", output = "http://tomcatmetrosoap.bilokhado/SoapCountryService/getCountriesResponse")
    public List<Country> getCountries();

}
