
package bilokhado.countrysoapclient.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapCountryServiceService", targetNamespace = "http://tomcatmetrosoap.bilokhado/", wsdlLocation = "http://localhost:8081/TomcatMetroSoap/?wsdl")
public class SoapCountryServiceService
    extends Service
{

    private final static URL SOAPCOUNTRYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPCOUNTRYSERVICESERVICE_EXCEPTION;
    private final static QName SOAPCOUNTRYSERVICESERVICE_QNAME = new QName("http://tomcatmetrosoap.bilokhado/", "SoapCountryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/TomcatMetroSoap/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPCOUNTRYSERVICESERVICE_WSDL_LOCATION = url;
        SOAPCOUNTRYSERVICESERVICE_EXCEPTION = e;
    }

    public SoapCountryServiceService() {
        super(__getWsdlLocation(), SOAPCOUNTRYSERVICESERVICE_QNAME);
    }

    public SoapCountryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPCOUNTRYSERVICESERVICE_QNAME, features);
    }

    public SoapCountryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPCOUNTRYSERVICESERVICE_QNAME);
    }

    public SoapCountryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPCOUNTRYSERVICESERVICE_QNAME, features);
    }

    public SoapCountryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapCountryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapCountryService
     */
    @WebEndpoint(name = "SoapCountryServicePort")
    public SoapCountryService getSoapCountryServicePort() {
        return super.getPort(new QName("http://tomcatmetrosoap.bilokhado/", "SoapCountryServicePort"), SoapCountryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapCountryService
     */
    @WebEndpoint(name = "SoapCountryServicePort")
    public SoapCountryService getSoapCountryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tomcatmetrosoap.bilokhado/", "SoapCountryServicePort"), SoapCountryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPCOUNTRYSERVICESERVICE_EXCEPTION!= null) {
            throw SOAPCOUNTRYSERVICESERVICE_EXCEPTION;
        }
        return SOAPCOUNTRYSERVICESERVICE_WSDL_LOCATION;
    }

}
